# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos: Lucia Sanjuan Perez  <br>
Url: https://github.com/.../03MAIR---Algoritmos-de-Optimizacion---2019/tree/master/SEMINARIO<br>
Problema:
> 1. Sesiones de doblaje <br>

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible. Los datos son:

Número de actores: 10

Número de tomas : 30

Actores/Tomas : https://bit.ly/36D8IuK

- 1 indica que el actor participa en la toma
- 0 en caso contrario



(*) La respuesta es obligatoria





                                        

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



En el peor de los casos consideraremos 30 días posibles (1 toma por día), cada toma tiene 30 opciones, por tanto tendríamos 30^30 posibilidades sin restricciones.

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


La estructura de datos que mejor se adapta es:

Lista de listas

dias = [
  
    [0, 5, 8, 10],   # Día 1

    [1, 2, 7],       # Día 2

    [3, 4, 6, 9]     # Día 3

]

El problema consiste en agrupar tomas en días, cada sublista es una lista y cada elemento una toma.

Esta estructura permite un número variable de días, es facil aplicar restricciones y calcular la función objetivo.

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

La función objetivo es una función que, dada una distribución de las tomas en días, calcula el coste total de contratación de los actores. Este coste se obtiene sumando, para cada día, el número de actores distintos que participan en las tomas asignadas a dicho día, ya que cada actor cobra una vez por día independientemente del número de tomas.

El problema es de minimización, ya que el objetivo es reducir el coste total asociado a la contratación de los actores, minimizando el número de días en los que cada actor debe acudir a la grabación.

In [ ]:
def coste_total(dias, data):
    total = 0

    for dia in dias: #Recorre cada día de la planificación
        #Selecciona las tomas del día y calcula qué actores participan
        actores = np.any(data[dia], axis=0)
        #Suma el número de actores distintos del día
        total += actores.sum()

    return total

Diseña un algoritmo para resolver el problema por fuerza bruta

Debido al elevado coste computacional del algoritmo de fuerza bruta, hemos reducido el data a 10 tomas y el máximo de días a 3 tomas por día.

In [ ]:
mejor_coste = float('inf')
mejor_solucion = None

data = np.array([
[1,1,1,1,1,0,0,0,0,0],
[0,0,1,1,1,0,0,0,0,0],
[0,1,0,0,1,0,1,0,0,0],
[1,1,0,0,0,0,1,1,0,0],
[0,1,0,1,0,0,0,1,0,0],
[1,1,0,1,1,0,0,0,0,0],
[1,1,0,1,1,0,0,0,0,0],
[1,1,0,0,0,1,0,0,0,0],
[1,1,0,1,0,0,0,0,0,0],
[1,1,0,0,0,1,0,0,1,0]
])

def backtracking(toma_actual, dias, data, max_tomas_dia):
    global mejor_coste, mejor_solucion

    if toma_actual == len(data):

        #Calculamos el coste de la solución completa
        coste = coste_total(dias, data)

        #Si es mejor que el mejor encontrado hasta ahora
        if coste < mejor_coste:
            mejor_coste = coste
            mejor_solucion = [d.copy() for d in dias]
        return

    ###Intentamos meter en días existentes
    for dia in dias:

        #Si el día no está lleno
        if len(dia) < max_tomas_dia:

            #Se crea un nuevo día con esta toma
            dia.append(toma_actual)
            #Exploramos esa rama
            backtracking(toma_actual + 1, dias, data, max_tomas_dia)
            #Deshacemos el cambio
            dia.pop()

    ###Creamos nuevo día
    dias.append([toma_actual])
    #Exploramos esa rama
    backtracking(toma_actual + 1, dias, data, max_tomas_dia)
    #Deshacemos el cambio
    dias.pop()

#Ejecución
max_tomas_dia = 3

backtracking(0, [], data, max_tomas_dia)

print("Mejor coste:", mejor_coste)
print("Mejor solución:", mejor_solucion)

Mejor coste: 19
Mejor solución: [[0, 1, 2], [3, 4, 8], [5, 6], [7, 9]]


(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

In [ ]:
import numpy as np

data = np.array([
[1,1,1,1,1,0,0,0,0,0],
[0,0,1,1,1,0,0,0,0,0],
[0,1,0,0,1,0,1,0,0,0],
[1,1,0,0,0,0,1,1,0,0],
[0,1,0,1,0,0,0,1,0,0],
[1,1,0,1,1,0,0,0,0,0],
[1,1,0,1,1,0,0,0,0,0],
[1,1,0,0,0,1,0,0,0,0],
[1,1,0,1,0,0,0,0,0,0],
[1,1,0,0,0,1,0,0,1,0],
[1,1,1,0,1,0,0,1,0,0],
[1,1,1,1,0,1,0,0,0,0],
[1,0,0,1,1,0,0,0,0,0],
[1,0,1,0,0,1,0,0,0,0],
[1,1,0,0,0,0,1,0,0,0],
[0,0,0,1,0,0,0,0,0,1],
[1,0,1,0,0,0,0,0,0,0],
[0,0,1,0,0,1,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0],
[1,0,1,1,1,0,0,0,0,0],
[0,0,0,0,0,1,0,1,0,0],
[1,1,1,1,0,0,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0],
[0,0,1,0,0,1,0,0,0,0],
[1,1,0,1,0,0,0,0,0,1],
[1,0,1,0,1,0,0,0,1,0],
[0,0,0,1,1,0,0,0,0,0],
[1,0,0,1,0,0,0,0,0,0],
[1,0,0,0,1,1,0,0,0,0],
[1,0,0,1,0,0,0,0,0,0]
])


#Suma cuántos actores distintos aparecen en ese día
def coste_parcial(dia, data):
    actores = np.any(data[dia], axis=0)
    return actores.sum()


def distribucion_dias(data, max_tomas_dia):

    #Lista de tomas que aún no se han asignado
    tomas_restantes = list(range(len(data)))

    #Solución final: lista de días
    dias = []

    #Mientras queden tomas por asignar
    while tomas_restantes:

        dia = []

        #Tomamos la primera toma como inicio del día
        actual = tomas_restantes.pop(0)
        dia.append(actual)

        #Rellenamos el día hasta el máximo permitido
        while len(dia) < max_tomas_dia and tomas_restantes:

            mejor_toma = None
            mejor_coste = float('inf')

            #Probamos cada toma candidata
            for t in tomas_restantes:

                #Simulamos añadir la toma al día actual
                candidato = dia + [t]

                #Calculamos el coste del día si añadimos esa toma
                coste = coste_parcial(candidato, data)

                #Nos quedamos con la mejor opción (menor coste)
                if coste < mejor_coste:
                    mejor_coste = coste
                    mejor_toma = t

            #Añadimos la mejor toma encontrada
            dia.append(mejor_toma)
            tomas_restantes.remove(mejor_toma)

        #Guardamos el día completo en la solución
        dias.append(dia)

    return dias

#Ejecución
max_tomas_dia = 6 #restricción max 6 tomas por día

dias = distribucion_dias(data, max_tomas_dia)

print("Distribución de días:", dias)
print("Coste total:", coste_total(dias, data))

######################
#Además para comparar con el algoritmo de fuerza bruta vamos a ejecutar este algoritmo con los mismos datos y max de tomas por día

data2 = np.array([
[1,1,1,1,1,0,0,0,0,0],
[0,0,1,1,1,0,0,0,0,0],
[0,1,0,0,1,0,1,0,0,0],
[1,1,0,0,0,0,1,1,0,0],
[0,1,0,1,0,0,0,1,0,0],
[1,1,0,1,1,0,0,0,0,0],
[1,1,0,1,1,0,0,0,0,0],
[1,1,0,0,0,1,0,0,0,0],
[1,1,0,1,0,0,0,0,0,0],
[1,1,0,0,0,1,0,0,1,0]
])

max_tomas_dia2 = 3 #Restricción max 6 tomas por día

dias = distribucion_dias(data2, max_tomas_dia2)

print("Distribución de días:", dias)
print("Coste total:", coste_total(dias, data2))


Distribución de días: [[0, 1, 5, 6, 8, 12], [2, 14, 3, 4, 26, 27], [7, 9, 13, 16, 17, 18], [10, 22, 19, 21, 29, 11], [15, 20, 23, 24, 28, 25]]
Coste total: 32
Distribución de días: [[0, 1, 5], [2, 3, 4], [6, 8, 7], [9]]
Coste total: 20


Como podemos ver al comparar con el algoritmo de fuerza bruta el coste que nos da nuestro algoritmo greedy es casi la óptima, esto sucede porque las decisiones tomadas en etapas iniciales no se revisan posteriormente.

(*)Calcula la complejidad del algoritmo

Para mejorar la complejidad del algoritmo de fuerza bruta, se propone un algoritmo heurístico de tipo greedy. Este algoritmo agrupa en cada día aquellas tomas que comparten el mayor número de actores, con el objetivo de reducir el número de actores distintos por día.

A diferencia del algoritmo de fuerza bruta, que explora todas las posibles combinaciones, el algoritmo greedy toma decisiones locales basadas en la similitud entre tomas, reduciendo significativamente el espacio de búsqueda.

Esto permite pasar de una complejidad exponencial a una complejidad polinómica, aproximadamente O(n^2 * m), lo que hace que el algoritmo sea aplicable a instancias de mayor tamaño, aunque no garantiza encontrar la solución óptima.

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Vamos a generar por ejemplo 20 tomas y 8 actores diferentes.

In [ ]:
import numpy as np

def generar_datos(n_tomas, n_actores, min_actores=1, max_actores=5):

    data = np.zeros((n_tomas, n_actores), dtype=int)

    for i in range(n_tomas):
        # número aleatorio de actores en la toma
        num_actores = np.random.randint(min_actores, max_actores + 1)

        # elegir actores sin repetir
        actores = np.random.choice(n_actores, num_actores, replace=False)

        # asignar 1 a esos actores
        data[i, actores] = 1

    return data

data_random = generar_datos(20, 8)

print(data_random)

[[0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [0 1 0 0 1 0 0 1]
 [1 1 1 1 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 1]
 [0 0 0 1 0 0 0 0]
 [1 1 0 1 1 0 1 0]
 [1 1 0 0 1 0 1 1]
 [0 1 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 1]
 [0 1 0 1 1 1 1 0]
 [0 1 0 0 0 0 1 0]
 [0 0 1 1 0 1 0 0]]


Aplica el algoritmo al juego de datos generado

In [ ]:
max_tomas_dia = 6

dias = distribucion_dias(data_random, max_tomas_dia)

print("Distribución de días:", dias)
print("Coste total:", coste_total(dias, data_random))

Distribución de días: [[0, 6, 7, 8, 16, 1], [2, 3, 4, 9, 5, 12], [10, 18, 15, 11, 14, 13], [17, 19]]
Coste total: 22
